# Generated by Django 4.0.1 on 2022-02-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('trips', '0002_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_date', models.DateTimeField(auto_now=True)),
                ('trip_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trips_desc', models.TextField(max_length=1500)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='trips.cities')),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_country', to='trips.countries')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='trips.cities')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_country', to='trips.countries')),
                ('trip_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.authuser')),
            ],
        ),
    ]
